on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  schedule:
    - cron: '45 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      #     cache: maven
      - name: Scrape ESPN
        run: backend\env\helpers\espn_getter.py
