on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  schedule:
    - cron: '35 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'
      #     cache: maven
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape ESPN
        run: python backend\env\helpers\espn_getter.py